// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIjvVSgpghSunPImQbdufYbtaHFTZyAfM',
    appId: '1:458198303726:web:1c159e23f90c928827c4ff',
    messagingSenderId: '458198303726',
    projectId: 'kharidle-280ed',
    authDomain: 'kharidle-280ed.firebaseapp.com',
    storageBucket: 'kharidle-280ed.firebasestorage.app',
    measurementId: 'G-Q5KV29743L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwd01gnXXucE-Ouc-8pjMETFjzxN1IcuY',
    appId: '1:458198303726:android:ab9b214a07b3016e27c4ff',
    messagingSenderId: '458198303726',
    projectId: 'kharidle-280ed',
    storageBucket: 'kharidle-280ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl1rtc8UvnAzXV5DikjmrCW53TAvzL-_g',
    appId: '1:458198303726:ios:427785514abbe71227c4ff',
    messagingSenderId: '458198303726',
    projectId: 'kharidle-280ed',
    storageBucket: 'kharidle-280ed.firebasestorage.app',
    iosBundleId: 'com.example.kharidLe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl1rtc8UvnAzXV5DikjmrCW53TAvzL-_g',
    appId: '1:458198303726:ios:427785514abbe71227c4ff',
    messagingSenderId: '458198303726',
    projectId: 'kharidle-280ed',
    storageBucket: 'kharidle-280ed.firebasestorage.app',
    iosBundleId: 'com.example.kharidLe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIjvVSgpghSunPImQbdufYbtaHFTZyAfM',
    appId: '1:458198303726:web:6c15847f01146cd327c4ff',
    messagingSenderId: '458198303726',
    projectId: 'kharidle-280ed',
    authDomain: 'kharidle-280ed.firebaseapp.com',
    storageBucket: 'kharidle-280ed.firebasestorage.app',
    measurementId: 'G-2XT11HL0L7',
  );
}
